using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace lovis.Controllers.License
{
    public class License
    {

        #region ATTRIBUTES

        public string Id { get; set; }
        public string IdLicense { get; set; }

        #endregion

        #region CONSTRUCTORS

        /// <summary>
        /// Empty constructor
        /// </summary>
        public License() { }

        /// <summary>
        /// Constructor filled with a License
        /// </summary>
        /// <param name="L"></param>
        public License(License L)
        {

        }

        /// <summary>
        /// Constructor generated by new user
        /// </summary>
        /// <param name="u"></param>
        public License(Users.Users u)
        {
            // New license
            string rnd = lovis.Security.CryptoUtils.RandomKey();
            Id = lovis.Security.CryptoUtils.SHA1HashStringForUTF8String(rnd);
            IdLicense = u.Username.Substring(0, 2) + "-" + lovis.Security.CryptoUtils.SHA256HashStringForUTF8String(rnd);

            // Add to database
            New();
        }

        #endregion

        #region NEW 

        /// <summary>
        /// New license
        /// </summary>
        /// <returns>42 lenght string idLicnse</returns>
        public void New()
        {
            // Add to database here
            // entityframeworks

        }

        #endregion

        #region EDIT

        /// <summary>
        /// Method to edit license, probably not going to be used.
        /// </summary>
        public void Edit()
        {

        }

        #endregion

        #region REMOVE

        /// <summary>
        /// Method that removes a license, probably not going to be used.
        /// </summary>
        public void Remove()
        {


        }

        #endregion


    }
}